default_platform(:android)

platform :android do
  lane :firebase_distribution do
    sh "flutter clean"
    sh "flutter build apk --release --flavor production --target lib/main.dart --no-tree-shake-icons"
    firebase_app_distribution(
        app: "1:437676062074:android:0394ea2188a8ea239312c3",
        firebase_cli_token: ENV["FIREBASE_TOKEN"],
        android_artifact_type: "APK",
        android_artifact_path: "../build/app/outputs/flutter-apk/app-production-release.apk",
        testers: "mohammadwork199700@gmail.com",
        release_notes: "New build from CI",
    )
  end
end
